### PR TITLE
Merging upstream

### PR DESCRIPTION
**Pull request by GearsAD**

### CODE REVIEW

**Comment by GearsAD** [comment]
This is Julia 1.0 compliant and the tests are working locally. Your tests are pretty solid, thanks for that! 

If you're happy with this we can transfer ownership to JuliaDatabases - we can either transfer yours or the forked repo, I feel a little strange just transferring the fork without discussing.

**Comment by jkaye2012** [comment]
I would prefer to integrate here and transfer if you don't mind. I will
take a look at this tomorrow and get back to you. Thank you for your work
on this!

**Comment by GearsAD** [comment]
That works great for me - thanks!

Let me see if I get get Travis to give a :+1:

**Comment by jkaye2012** [comment]
Sorry for the delay, changes look good.

**Pull request merged**
