### PR TITLE
fix returned type of *scan

### PR DESCRIPTION
**Pull request by ylxdzsw**
see #28 .

this PR changed the return type of `*scan` methods. But it still passes all tests :).

### CODE REVIEW

**Comment by jkaye2012** [comment]
Great change! Could you add a few integration test cases to redis_tests.jl and make sure that those function properly? This will help to prevent future regressions for the scan commands.

**Comment by ylxdzsw** [comment]
I added tests, and I did found another bug of `zscan` during tests, which not only returns elements but also their scores.

**Comment by merl-dev** [comment]
@ylxdzsw: I recommend you submit these changes after I have made my PR this weekend, as per #30 since the use of `Dict` for input to sorted sets has to go. Alternatively, I could incorporate your changes making reference to your issue.  Up to you and  @jkaye2012.

**Comment by merl-dev** [comment]
Another option, since I have completed about 80% of the work, would be for me to submit a PR now.  Again, I defer to your wishes.

**Comment by ylxdzsw** [comment]
Both seems OK for me, but I find little conflicts till now(only some test cases?). I think it doesn't matter too much, a simple `git rebase` with a few changes would solve it.

**Comment by merl-dev** [comment]
The last 20% is gonna take the longest, as @jkaye2012 pointed out, a satisfactory and performant solution to the 'NIL' will likely involve `Nullable` and thus a significant change in the API.

**Comment by merl-dev** [comment]
The Javascript package for Redis, ioredis, also has an streaming feature that we could implement for the *SCAN commands, in addition to the standard commands.. This pattern allows the user to iterate through the results without having to keep track of the cursor, see https://github.com/luin/ioredis.

**Comment by jkaye2012** [comment]
If we don't do it as part of this commit, we should definitely create a separate feature request for the SCAN iterator. It's very useful to end users.

**Comment by merl-dev** [comment]
Yes, I've used that feature of the ioredis library and will need something like it for Julia's client.  I just need to finalize an interface that incorporates Nullable without affecting performance.  Node is simple, they want everything stringified, whereas in Julia we would like to be able to easily use Int's, Floats or whatever, without incurring the performance hit for type instability.  Not sure yet if we need a new type or just fiddle with the convert_response methods.

**Comment by jkaye2012** [comment]
I think it could be done pretty easily by adding convert_response methods for the Nullables then modifying commands.jl to dispatch the return values back as Nullable so that they use the specialized convert_response methods.

**Comment by merl-dev** [comment]
As in this?
```
function convert_response{T}(::Type{T}, response)
    if response == nothing 
       Nullable{T}() 
    elseif T<:Number 
       tryparse(T, response)
    else
       response
    end
end
```
This is fine for all the simple responses, needs to be extended for all the different Collection types

**Comment by merl-dev** [comment]
I am very curious about performance here

**Comment by merl-dev** [comment]
for arrays:
```
function convert_response{T}(::Type{Array{T,1}}, response)
    if response == nothing 
       return Array{Nullable{T}, 1}() 
    else
        r = Array{Nullable{T},1}()
        for item in response
            push!(r, tryparse(T, item))
        end
        return r
    end
end
```

**Comment by merl-dev** [comment]
and this also comes out clean checking for type stability, for `Array{AbstractString, 1}`
```
function convert_response{T<:AbstractString}(::Type{Array{T,1}}, response)
    if response == nothing
        Array{Nullable{T}, 1}()
   else
        r = Array{Nullable{T},1}()
        for item in response
            push!(r, Nullable{T}(item))
        end
        r
    end
end
```

**Comment by merl-dev** [comment]
OK, to summarize, type stable methods for `Number`s and `String`s, and `Array`s thereof:

```
function convert_response{T<:Number}(::Type{T}, response)
    if response == nothing
       Nullable{T}()
    else
       tryparse(T, response)
    end
end

function convert_response{T<:AbstractString}(::Type{T}, response)
    if response == nothing
       Nullable{T}()
    else
       Nullable{T}(response)
    end
end

function convert_response{T<:Number}(::Type{Array{T,1}}, response)
    if response == nothing
        Array{Nullable{T}, 1}()
   else
        r = Array{Nullable{T},1}()
        for item in response
            push!(r, tryparse(T, item))
        end
        r
    end
end

function convert_response{T<:AbstractString}(::Type{Array{T,1}}, response)
    if response == nothing
        Array{Nullable{T}, 1}()
   else
        r = Array{Nullable{T},1}()
        for item in response
            push!(r, Nullable{T}(item))
        end
        r
    end
end

```

**Comment by merl-dev** [comment]
Now we need to convert the other types, and perhaps have easier access to the underlying data when there are no nulls involved.

**Comment by ylxdzsw** [comment]
I like the idea of returning an Iterator for *scan methods. I can implement it after you have done your works @merl-dev, and so that make it fit your new API.

**Comment by merl-dev** [comment]
Great!  I hope to be done with the type issues and tests sometime this w/e.

**Comment by merl-dev** [comment]
Completed integrating the `Nullable`s interface, maybe more testing required, but this passes all the existing tests.

```
######## Type Conversions #########

convert_response(::Type{Float64}, response) = float(response)::Float64
convert_response(::Type{Bool}, response::AbstractString) = response == "OK" || response == "QUEUED" ? true : false
convert_response(::Type{Bool}, response::Integer) = response == 1 ? true : false
convert_response(::Type{Set{AbstractString}}, response) = Set{AbstractString}(response)
convert_response(::Type{OrderedSet{AbstractString}}, response) = OrderedSet{AbstractString}(response)

function convert_response(::Type{Dict{AbstractString, AbstractString}}, response)
    iseven(length(response)) || throw(ClientException("Response could not be converted to Dict"))
    retdict = Dict{AbstractString, AbstractString}()
    for i=1:2:length(response)
        retdict[response[i]] = response[i+1]
    end
    retdict
end

function convert_eval_response(::Any, response)
    if response == nothing
        Nullable()
    else
        response
    end
end

import Base: ==
=={T<:AbstractString, U<:AbstractString}(A::Nullable{T}, B::Nullable{U}) = get(A) == get(B)
=={T<:Number, U<:Number}(A::Nullable{T}, B::Nullable{U}) = get(A) == get(B)

convert_response(::Type{AbstractString}, response) = string(response)
convert_response(::Type{Integer}, response) = response

function convert_response(::Type{Array{AbstractString, 1}}, response)
    r = Array{AbstractString, 1}()
    for item in response
        push!(r, item)
    end
    r
end

function convert_response{T<:Number}(::Type{Nullable{T}}, response)
    if response == nothing
       Nullable{T}()
   elseif issubtype(typeof(response),T)
        Nullable{T}(response)
    else
       tryparse(T, response)
    end
end

function convert_response{T<:AbstractString}(::Type{Nullable{T}}, response)
    if response == nothing
       Nullable{T}()
    else
       Nullable{T}(response)
    end
end

# redundant
function convert_response{T<:Number}(::Type{Array{Nullable{T}, 1}}, response)
    if response == nothing
        Array{Nullable{T}, 1}()
   else
        r = Array{Nullable{T},1}()
        for item in response
            push!(r, tryparse(T, item))
        end
        r
    end
end

function convert_response{T<:AbstractString}(::Type{Array{Nullable{T}, 1}}, response)
    if response == nothing
        Array{Nullable{T}, 1}()
   else
        r = Array{Nullable{T},1}()
        for item in response
            push!(r, Nullable{T}(item))
        end
        r
    end
end
```

**Comment by merl-dev** [comment]
overloading Base.== for `Nullable` was required since Nullable(1) == Nullable(1) fails, as per issue #13207 of Julia Base, https://github.com/JuliaLang/julia/issues/13207

**Comment by ylxdzsw** [comment]
OK, I will wait your changes merged and make a new PR based on that.

**Comment by merl-dev** [comment]
@ylxdzsw see the last comment to my open PR.

**Pull request closed without merging**
